# Generated by Django 5.2.17 on 2026-09-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrubbing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterModelOptions(
            name='sanitizationlog',
            options={'verbose_name': 'Sanitization Log', 'verbose_name_plural': 'Sanitization Logs'},
        ),
    ]
